### 상품 추가
POST http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnMEhoUmhSMGxMVC8vZ1NxcFp0TnFvdmdySkRURHp3T3J3ZUk2MWVVSGF3PSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjc3MzI2NTMxLCJleHAiOjE2Nzc0MTI5MzF9.3jvgFgv3NF2zVLHYNWGTOy0pihE6nBfFhFTWsEjJXGM

{
  "description": "상품 설명",
  "items": [
    {
      "count": 1,
      "name": "270",
      "price": 100000
    }
  ],
  "name": "나이키 에어포스2"
}

### 상품 아이템 추가
POST http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnMEhoUmhSMGxMVC8vZ1NxcFp0TnFvdmdySkRURHp3T3J3ZUk2MWVVSGF3PSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjc3MzI2NTMxLCJleHAiOjE2Nzc0MTI5MzF9.3jvgFgv3NF2zVLHYNWGTOy0pihE6nBfFhFTWsEjJXGM

{
  "productId": 1,
  "count": 1,
  "name": "280",
  "price": 100000
}

### 상품 수정
PUT http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnMEhoUmhSMGxMVC8vZ1NxcFp0TnFvdmdySkRURHp3T3J3ZUk2MWVVSGF3PSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjc3MzI2NTMxLCJleHAiOjE2Nzc0MTI5MzF9.3jvgFgv3NF2zVLHYNWGTOy0pihE6nBfFhFTWsEjJXGM

{
  "description": "상품 설명",
  "items": [
    {
      "id": 1,
      "count": 1,
      "name": "280",
      "price": 100000
    }
  ],
  "id": 1,
  "name": "나이키 에어포스 한정판"
}

### 상품 아이템 수정
PUT http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnMEhoUmhSMGxMVC8vZ1NxcFp0TnFvdmdySkRURHp3T3J3ZUk2MWVVSGF3PSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjc3MzI2NTMxLCJleHAiOjE2Nzc0MTI5MzF9.3jvgFgv3NF2zVLHYNWGTOy0pihE6nBfFhFTWsEjJXGM

{
  "id": 1,
  "count": 1,
  "name": "260",
  "price": 100000
}

### 상품 삭제
DELETE http://localhost:8082/seller/product?id=1
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnMEhoUmhSMGxMVC8vZ1NxcFp0TnFvdmdySkRURHp3T3J3ZUk2MWVVSGF3PSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjc3MzI2NTMxLCJleHAiOjE2Nzc0MTI5MzF9.3jvgFgv3NF2zVLHYNWGTOy0pihE6nBfFhFTWsEjJXGM

### 상품 아이템 삭제
DELETE http://localhost:8082/seller/product/item?id=2
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnMEhoUmhSMGxMVC8vZ1NxcFp0TnFvdmdySkRURHp3T3J3ZUk2MWVVSGF3PSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjc3MzI2NTMxLCJleHAiOjE2Nzc0MTI5MzF9.3jvgFgv3NF2zVLHYNWGTOy0pihE6nBfFhFTWsEjJXGM

### 상품 검색
GET http://localhost:8082/search/product?name=나이키
Content-Type: application/json

### 상품 디테일 검색
GET http://localhost:8082/search/product/detail?productId=2
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnMEhoUmhSMGxMVC8vZ1NxcFp0TnFvdmdySkRURHp3T3J3ZUk2MWVVSGF3PSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjc3MzI2NTMxLCJleHAiOjE2Nzc0MTI5MzF9.3jvgFgv3NF2zVLHYNWGTOy0pihE6nBfFhFTWsEjJXGM

### 카트 추가
POST http://localhost:8082/customer/cart
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoTG0vdGs1aVlpbEJXTmkreitob0gwL0x1a0VWam5YTllOTUt2Q2RIZ293PSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2NzczMjY1OTAsImV4cCI6MTY3NzQxMjk5MH0.9v7rrGkzgzrnOR5ytIow1MWXyerkoJIjyx5wRPLu-vI

{
  "description": "상품 설명",
  "id": 1,
  "items": [
    {
      "count": 1,
      "id": 1,
      "name": "270",
      "price": 100000
    }
  ],
  "name": "나이키 에어포스2",
  "sellerId": 1
}

### 카트 조회
GET http://localhost:8082/customer/cart
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoTG0vdGs1aVlpbEJXTmkreitob0gwL0x1a0VWam5YTllOTUt2Q2RIZ293PSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2NzczMjY1OTAsImV4cCI6MTY3NzQxMjk5MH0.9v7rrGkzgzrnOR5ytIow1MWXyerkoJIjyx5wRPLu-vI

### 카트 주문
POST http://localhost:8082/customer/cart/order
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoTG0vdGs1aVlpbEJXTmkreitob0gwL0x1a0VWam5YTllOTUt2Q2RIZ293PSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2NzczMjY1OTAsImV4cCI6MTY3NzQxMjk5MH0.9v7rrGkzgzrnOR5ytIow1MWXyerkoJIjyx5wRPLu-vI

{
  "customerId": 1,
  "products": [
    {
      "id": 1,
      "sellerId": 1,
      "name": "나이키 에어포스2",
      "description": "상품 설명",
      "items": [
        {
          "id": 1,
          "name": "270",
          "count": 1,
          "price": 100000
        }
      ]
    }
  ],
  "messages": []
}
